### PR TITLE
Merge windowing into development

### PR DESCRIPTION
**Pull request by Goldscar1**
#### Summary
Add windowing

#### Explanation
The windowing branch adds dependencies and code to create a cross-platform window.

This is a requirement for things like rendering.

---
**Status**
*Apart from the GitHub action ran automatically on your PR, please confirm the following:*

- [X] code changes have been tested using appropiate testing methods, or there are no code changes.

### CODE REVIEW

**Comment by l-zeuch** [comment]
Checks are failing still, I'll re-run them.
You tested `cargo build`, right?

**Comment by Goldscar1** [comment]
Seems that a curly bracket escaped...
Should be fixed now.

**Comment by l-zeuch** [comment]
Let's wait for the checks and then we are good to go!

**Review by l-zeuch — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
